"""empty message

Revision ID: 0306bafd74a9
Revises: 8d567cff4eb0
Create Date: 2016-11-16 16:52:53.242866

"""

# revision identifiers, used by Alembic.
revision = '0306bafd74a9'
down_revision = '8d567cff4eb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
